### PR TITLE
Added Catalan locale

### PR DESCRIPTION
**Pull request by metalbass**

### CODE REVIEW

**Review by NoxyNixie — APPROVED** [review]
I sure hope no vulgarity is in here as I can't read this, thanks though ;)

**Comment by metalbass** [comment]
No vulgarities present, no worries 😄 

I just noticed that the file I pushed is called /locale/ca/en.cfg, which is not too nice.
This is due we're using [this project](https://github.com/dima74/factorio-mods-localization) so that localizations can be done on [Crowdin](https://crowdin.com/project/factorio-mods-localization), like the ones of the base game.

Right now, my fork of the repo will automatically receive all translations made on Crowdin and I can keep making PRs to your repo when there's new content, but the ideal scenario would be that your repo is the one linked with Crowdin and there's no need to keep making and approving PRs for localization changes. 😋 

There's only the catch that the localization file names need to be the same between languages, so that Crowdin knows how to handle them. Renaming all of them to locale.cfg worked just fine in my PC, so that's all that's needed.

**Comment by NoxyNixie** [comment]
hm I see. the reason why I name them the locale they represent is so that when I have them open in the editor I can see immediately which one I am editing.

Having multiple ones open named locale.cfg ... well gets confusing.

I could rename them for all my mods to simply `locale.cfg` since honestly I don't even translate to my own native language ;).

Would that work better for you?

**Comment by metalbass** [comment]
That would be awesome, thank you! :)

What do you think about integrating the localization helper? It's as easy as giving it permissions into the repo.

**Comment by NoxyNixie** [comment]
I'm not familiar with this localization helper thingy so wouldn't know where to start however I'm not opposed to allowing it access. You'd have to give me pointers to what and where though ;)

**Comment by NoxyNixie** [comment]
Alright I think I figured it out and all repositories should now be accessible through the thingy. Looks like your forks are duplicating the effort now though ;)

**Comment by metalbass** [comment]
Great!
Yes, I'll get rid of them today :)

Thank you!

**Pull request merged**
